server:
  port: 8095

spring:
  application:
    name: skill-k8s

management:
  endpoints:
    web:
      exposure:
        include: health,info

k8s:
  master-url: ${K8S_MASTER_URL:}
  token: ${K8S_TOKEN:}
  namespace: ${K8S_NAMESPACE:default}
  mock-enabled: ${K8S_MOCK_ENABLED:true}
